name: envai-book
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - ghp-import
  - hvplot
  - intake
  - intake-xarray
  - bottleneck
  - pooch
  - pytorch==1.8.0
  - torchvision==0.9.0
  - geoviews
  - pip
  - pip:
      - scikit-image
      - opencv-python