name: envds-book
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book
  - matplotlib
  - numpy
  - bottleneck
  - pooch
  - urllib3
  - opencv
  - hvplot
  - datashader
  - intake
  - intake-xarray
  - iris==3.0.1
  - pytorch==1.9.0
  - torchvision==0.10.0
  - tensorflow==2.2.0
#  - rasterio
  - pip
  - pip:
        - aiohttp
        - albumentations
        - scikit-image
        - pycurl
        - git+https://github.com/ESM-VFC/intake_zenodo_fetcher.git