name: envai-book-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - ghp-import
  - hvplot
  - intake
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - pooch
  - pytorch
  - geoviews
  - pip
  - pip:
      - scikit-image
      - opencv-python