name: envai-book
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - ghp-import
  - bottleneck
  - urllib3
  - pip
  - pip:
      - aiohttp