[build]
  base = "book"
  command = "wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh . && chmod +x Miniconda3-py38_4.10.3-Linux-x86_64.sh && sh ./Miniconda3-py38_4.10.3-Linux-x86_64.sh"
  publish = "book/_build/html"