[build]
  base = "book"
  command = "wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh && which conda && export PATH='/home/<user>/miniconda3/bin:$PATH' && conda install pandas -y"
  publish = "book/_build/html"