name: "\U0001F4D7 Notebook Request"
description: Log a notebook idea/
title: "[NB]: "
labels: ["demonstrator", "notebook"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to log a demonstrator/notebook idea!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: What is the demostrator about?
      description: Please provide further context of the pourpose of the notebook.
      placeholder: Tell us enough context (data sources (and links), packages, codebase, etc)
      value: ""
    validations:
      required: true
  - type: dropdown
    id: Component
    attributes:
      label: Data Science Component
      description: Which data science component is targeted?
      options:
        - Sensor visualisation
        - Preprocessing
        - Modelling
        - Post-processing
        - Other
    validations:
      required: true
  - type: checkboxes
    id: nb-checklist
    attributes:
      label: Minimal setup for publication
      description: Please check the following items which will help us to assess the feasibility of the notebook.
      options:
        - label: Input data, pipeline and/or model are public with license/citation
          required: false
        - label: Will the proposed notebook reuse existing codebase?
          required: false
        - label: Will the notebook use open-source packages?
          required: false
        - label: Are any existing publications associated to the notebook?
          required: false